name: Auto approve

on:
  repository_dispatch:
    types: [finished-move]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: ${{ github.event.label.name == 'automerge' }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          pull-request-number: "${{ github.event.client_payload.pr }}"

      - name: Move is valid (Repository Dispatch)
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: approved
          client-payload: '{"pr": "${{ github.event.client_payload.pr }}"'




