name: automerge
on:
  repository_dispatch:
    types: [approved]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-approve
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: "${{ github.event.client_payload.pr }}"
