name: Auto approve

on:
  repository_dispatch:
    types: [board-regenerated]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'TomCasavant' || github.actor == 'github-actions'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # if approved, run the action
      - name: Approved PR Dispatch
        uses: peter-evans/repository-dispatch@v1
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'TomCasavant' || github.actor == 'github-actions'
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: pr-approved
