name: Chess Move Allowed?
on:
  push:
    branches: [ make-move ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        id: test
        run: pytest -vv
      - name: Move is valid (Repository Dispatch)
        uses: peter-evans/repository-dispatch@v1
        # If test was successful
        if: steps.test.outcome == 'success'
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: move-valid
